apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: glubot-backoffice
  description: |
    Glubot main back office frontend
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: glubo
  lifecycle: experimental
